### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by kshitijsachan** [facebookresearch/torchdim#10]
I really like the philosophy behind this library. It looks like there hasn't been any activity for a few months - are you still actively developing it and is the plan still to merge it with functorch?

**Comment by zdevito** [comment]
Didn't see this earlier -- it is still being maintained, but the code has moved into `functorch.dim` in the PyTorch repo. On newer versions of pytorch it can be used by just doing `from functorch.dim import dims`.
